// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: dsm.proto
#ifndef GRPC_dsm_2eproto__INCLUDED
#define GRPC_dsm_2eproto__INCLUDED

#include "dsm.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace dsm {

class dsm_service final {
 public:
  static constexpr char const* service_full_name() {
    return "dsm.dsm_service";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status send_dsm_request(::grpc::ClientContext* context, const ::dsm::dsm_request& request, ::dsm::dsm_reply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dsm::dsm_reply>> Asyncsend_dsm_request(::grpc::ClientContext* context, const ::dsm::dsm_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dsm::dsm_reply>>(Asyncsend_dsm_requestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dsm::dsm_reply>> PrepareAsyncsend_dsm_request(::grpc::ClientContext* context, const ::dsm::dsm_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dsm::dsm_reply>>(PrepareAsyncsend_dsm_requestRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void send_dsm_request(::grpc::ClientContext* context, const ::dsm::dsm_request* request, ::dsm::dsm_reply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void send_dsm_request(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::dsm::dsm_reply* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::dsm::dsm_reply>* Asyncsend_dsm_requestRaw(::grpc::ClientContext* context, const ::dsm::dsm_request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::dsm::dsm_reply>* PrepareAsyncsend_dsm_requestRaw(::grpc::ClientContext* context, const ::dsm::dsm_request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status send_dsm_request(::grpc::ClientContext* context, const ::dsm::dsm_request& request, ::dsm::dsm_reply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dsm::dsm_reply>> Asyncsend_dsm_request(::grpc::ClientContext* context, const ::dsm::dsm_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dsm::dsm_reply>>(Asyncsend_dsm_requestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dsm::dsm_reply>> PrepareAsyncsend_dsm_request(::grpc::ClientContext* context, const ::dsm::dsm_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dsm::dsm_reply>>(PrepareAsyncsend_dsm_requestRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void send_dsm_request(::grpc::ClientContext* context, const ::dsm::dsm_request* request, ::dsm::dsm_reply* response, std::function<void(::grpc::Status)>) override;
      void send_dsm_request(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::dsm::dsm_reply* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::dsm::dsm_reply>* Asyncsend_dsm_requestRaw(::grpc::ClientContext* context, const ::dsm::dsm_request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::dsm::dsm_reply>* PrepareAsyncsend_dsm_requestRaw(::grpc::ClientContext* context, const ::dsm::dsm_request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_send_dsm_request_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status send_dsm_request(::grpc::ServerContext* context, const ::dsm::dsm_request* request, ::dsm::dsm_reply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_send_dsm_request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_send_dsm_request() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_send_dsm_request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_dsm_request(::grpc::ServerContext* context, const ::dsm::dsm_request* request, ::dsm::dsm_reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestsend_dsm_request(::grpc::ServerContext* context, ::dsm::dsm_request* request, ::grpc::ServerAsyncResponseWriter< ::dsm::dsm_reply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_send_dsm_request<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_send_dsm_request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_send_dsm_request() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::dsm::dsm_request, ::dsm::dsm_reply>(
          [this](::grpc::ServerContext* context,
                 const ::dsm::dsm_request* request,
                 ::dsm::dsm_reply* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->send_dsm_request(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_send_dsm_request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_dsm_request(::grpc::ServerContext* context, const ::dsm::dsm_request* request, ::dsm::dsm_reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void send_dsm_request(::grpc::ServerContext* context, const ::dsm::dsm_request* request, ::dsm::dsm_reply* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_send_dsm_request<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_send_dsm_request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_send_dsm_request() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_send_dsm_request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_dsm_request(::grpc::ServerContext* context, const ::dsm::dsm_request* request, ::dsm::dsm_reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_send_dsm_request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_send_dsm_request() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_send_dsm_request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_dsm_request(::grpc::ServerContext* context, const ::dsm::dsm_request* request, ::dsm::dsm_reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestsend_dsm_request(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_send_dsm_request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_send_dsm_request() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->send_dsm_request(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_send_dsm_request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_dsm_request(::grpc::ServerContext* context, const ::dsm::dsm_request* request, ::dsm::dsm_reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void send_dsm_request(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_send_dsm_request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_send_dsm_request() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::dsm::dsm_request, ::dsm::dsm_reply>(std::bind(&WithStreamedUnaryMethod_send_dsm_request<BaseClass>::Streamedsend_dsm_request, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_send_dsm_request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status send_dsm_request(::grpc::ServerContext* context, const ::dsm::dsm_request* request, ::dsm::dsm_reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedsend_dsm_request(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::dsm::dsm_request,::dsm::dsm_reply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_send_dsm_request<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_send_dsm_request<Service > StreamedService;
};

}  // namespace dsm


#endif  // GRPC_dsm_2eproto__INCLUDED
