// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mutex.proto
#ifndef GRPC_mutex_2eproto__INCLUDED
#define GRPC_mutex_2eproto__INCLUDED

#include "mutex.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace mutex {

// Defines the service
// need to check: can I do multiple rpc's or services?
class mutex_service final {
 public:
  static constexpr char const* service_full_name() {
    return "mutex.mutex_service";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Function invoked to send the request
    virtual ::grpc::Status send_mutex_request(::grpc::ClientContext* context, const ::mutex::mutex_request& request, ::mutex::mutex_reply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mutex::mutex_reply>> Asyncsend_mutex_request(::grpc::ClientContext* context, const ::mutex::mutex_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mutex::mutex_reply>>(Asyncsend_mutex_requestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mutex::mutex_reply>> PrepareAsyncsend_mutex_request(::grpc::ClientContext* context, const ::mutex::mutex_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mutex::mutex_reply>>(PrepareAsyncsend_mutex_requestRaw(context, request, cq));
    }
    virtual ::grpc::Status send_deferred_reply(::grpc::ClientContext* context, const ::mutex::mutex_deferred_reply& request, ::mutex::mutex_reply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mutex::mutex_reply>> Asyncsend_deferred_reply(::grpc::ClientContext* context, const ::mutex::mutex_deferred_reply& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mutex::mutex_reply>>(Asyncsend_deferred_replyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mutex::mutex_reply>> PrepareAsyncsend_deferred_reply(::grpc::ClientContext* context, const ::mutex::mutex_deferred_reply& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mutex::mutex_reply>>(PrepareAsyncsend_deferred_replyRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Function invoked to send the request
      virtual void send_mutex_request(::grpc::ClientContext* context, const ::mutex::mutex_request* request, ::mutex::mutex_reply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void send_mutex_request(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mutex::mutex_reply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void send_deferred_reply(::grpc::ClientContext* context, const ::mutex::mutex_deferred_reply* request, ::mutex::mutex_reply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void send_deferred_reply(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mutex::mutex_reply* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mutex::mutex_reply>* Asyncsend_mutex_requestRaw(::grpc::ClientContext* context, const ::mutex::mutex_request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mutex::mutex_reply>* PrepareAsyncsend_mutex_requestRaw(::grpc::ClientContext* context, const ::mutex::mutex_request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mutex::mutex_reply>* Asyncsend_deferred_replyRaw(::grpc::ClientContext* context, const ::mutex::mutex_deferred_reply& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mutex::mutex_reply>* PrepareAsyncsend_deferred_replyRaw(::grpc::ClientContext* context, const ::mutex::mutex_deferred_reply& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status send_mutex_request(::grpc::ClientContext* context, const ::mutex::mutex_request& request, ::mutex::mutex_reply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mutex::mutex_reply>> Asyncsend_mutex_request(::grpc::ClientContext* context, const ::mutex::mutex_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mutex::mutex_reply>>(Asyncsend_mutex_requestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mutex::mutex_reply>> PrepareAsyncsend_mutex_request(::grpc::ClientContext* context, const ::mutex::mutex_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mutex::mutex_reply>>(PrepareAsyncsend_mutex_requestRaw(context, request, cq));
    }
    ::grpc::Status send_deferred_reply(::grpc::ClientContext* context, const ::mutex::mutex_deferred_reply& request, ::mutex::mutex_reply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mutex::mutex_reply>> Asyncsend_deferred_reply(::grpc::ClientContext* context, const ::mutex::mutex_deferred_reply& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mutex::mutex_reply>>(Asyncsend_deferred_replyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mutex::mutex_reply>> PrepareAsyncsend_deferred_reply(::grpc::ClientContext* context, const ::mutex::mutex_deferred_reply& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mutex::mutex_reply>>(PrepareAsyncsend_deferred_replyRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void send_mutex_request(::grpc::ClientContext* context, const ::mutex::mutex_request* request, ::mutex::mutex_reply* response, std::function<void(::grpc::Status)>) override;
      void send_mutex_request(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mutex::mutex_reply* response, std::function<void(::grpc::Status)>) override;
      void send_deferred_reply(::grpc::ClientContext* context, const ::mutex::mutex_deferred_reply* request, ::mutex::mutex_reply* response, std::function<void(::grpc::Status)>) override;
      void send_deferred_reply(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mutex::mutex_reply* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::mutex::mutex_reply>* Asyncsend_mutex_requestRaw(::grpc::ClientContext* context, const ::mutex::mutex_request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mutex::mutex_reply>* PrepareAsyncsend_mutex_requestRaw(::grpc::ClientContext* context, const ::mutex::mutex_request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mutex::mutex_reply>* Asyncsend_deferred_replyRaw(::grpc::ClientContext* context, const ::mutex::mutex_deferred_reply& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mutex::mutex_reply>* PrepareAsyncsend_deferred_replyRaw(::grpc::ClientContext* context, const ::mutex::mutex_deferred_reply& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_send_mutex_request_;
    const ::grpc::internal::RpcMethod rpcmethod_send_deferred_reply_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Function invoked to send the request
    virtual ::grpc::Status send_mutex_request(::grpc::ServerContext* context, const ::mutex::mutex_request* request, ::mutex::mutex_reply* response);
    virtual ::grpc::Status send_deferred_reply(::grpc::ServerContext* context, const ::mutex::mutex_deferred_reply* request, ::mutex::mutex_reply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_send_mutex_request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_send_mutex_request() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_send_mutex_request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_mutex_request(::grpc::ServerContext* context, const ::mutex::mutex_request* request, ::mutex::mutex_reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestsend_mutex_request(::grpc::ServerContext* context, ::mutex::mutex_request* request, ::grpc::ServerAsyncResponseWriter< ::mutex::mutex_reply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_send_deferred_reply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_send_deferred_reply() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_send_deferred_reply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_deferred_reply(::grpc::ServerContext* context, const ::mutex::mutex_deferred_reply* request, ::mutex::mutex_reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestsend_deferred_reply(::grpc::ServerContext* context, ::mutex::mutex_deferred_reply* request, ::grpc::ServerAsyncResponseWriter< ::mutex::mutex_reply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_send_mutex_request<WithAsyncMethod_send_deferred_reply<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_send_mutex_request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_send_mutex_request() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::mutex::mutex_request, ::mutex::mutex_reply>(
          [this](::grpc::ServerContext* context,
                 const ::mutex::mutex_request* request,
                 ::mutex::mutex_reply* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->send_mutex_request(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_send_mutex_request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_mutex_request(::grpc::ServerContext* context, const ::mutex::mutex_request* request, ::mutex::mutex_reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void send_mutex_request(::grpc::ServerContext* context, const ::mutex::mutex_request* request, ::mutex::mutex_reply* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_send_deferred_reply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_send_deferred_reply() {
      ::grpc::Service::experimental().MarkMethodCallback(1,
        new ::grpc::internal::CallbackUnaryHandler< ::mutex::mutex_deferred_reply, ::mutex::mutex_reply>(
          [this](::grpc::ServerContext* context,
                 const ::mutex::mutex_deferred_reply* request,
                 ::mutex::mutex_reply* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->send_deferred_reply(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_send_deferred_reply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_deferred_reply(::grpc::ServerContext* context, const ::mutex::mutex_deferred_reply* request, ::mutex::mutex_reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void send_deferred_reply(::grpc::ServerContext* context, const ::mutex::mutex_deferred_reply* request, ::mutex::mutex_reply* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_send_mutex_request<ExperimentalWithCallbackMethod_send_deferred_reply<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_send_mutex_request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_send_mutex_request() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_send_mutex_request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_mutex_request(::grpc::ServerContext* context, const ::mutex::mutex_request* request, ::mutex::mutex_reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_send_deferred_reply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_send_deferred_reply() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_send_deferred_reply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_deferred_reply(::grpc::ServerContext* context, const ::mutex::mutex_deferred_reply* request, ::mutex::mutex_reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_send_mutex_request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_send_mutex_request() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_send_mutex_request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_mutex_request(::grpc::ServerContext* context, const ::mutex::mutex_request* request, ::mutex::mutex_reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestsend_mutex_request(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_send_deferred_reply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_send_deferred_reply() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_send_deferred_reply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_deferred_reply(::grpc::ServerContext* context, const ::mutex::mutex_deferred_reply* request, ::mutex::mutex_reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestsend_deferred_reply(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_send_mutex_request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_send_mutex_request() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->send_mutex_request(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_send_mutex_request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_mutex_request(::grpc::ServerContext* context, const ::mutex::mutex_request* request, ::mutex::mutex_reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void send_mutex_request(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_send_deferred_reply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_send_deferred_reply() {
      ::grpc::Service::experimental().MarkMethodRawCallback(1,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->send_deferred_reply(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_send_deferred_reply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_deferred_reply(::grpc::ServerContext* context, const ::mutex::mutex_deferred_reply* request, ::mutex::mutex_reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void send_deferred_reply(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_send_mutex_request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_send_mutex_request() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::mutex::mutex_request, ::mutex::mutex_reply>(std::bind(&WithStreamedUnaryMethod_send_mutex_request<BaseClass>::Streamedsend_mutex_request, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_send_mutex_request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status send_mutex_request(::grpc::ServerContext* context, const ::mutex::mutex_request* request, ::mutex::mutex_reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedsend_mutex_request(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mutex::mutex_request,::mutex::mutex_reply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_send_deferred_reply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_send_deferred_reply() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::mutex::mutex_deferred_reply, ::mutex::mutex_reply>(std::bind(&WithStreamedUnaryMethod_send_deferred_reply<BaseClass>::Streamedsend_deferred_reply, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_send_deferred_reply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status send_deferred_reply(::grpc::ServerContext* context, const ::mutex::mutex_deferred_reply* request, ::mutex::mutex_reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedsend_deferred_reply(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mutex::mutex_deferred_reply,::mutex::mutex_reply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_send_mutex_request<WithStreamedUnaryMethod_send_deferred_reply<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_send_mutex_request<WithStreamedUnaryMethod_send_deferred_reply<Service > > StreamedService;
};

}  // namespace mutex


#endif  // GRPC_mutex_2eproto__INCLUDED
